# Generated by Django 5.0.2 on 2024-03-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_reviews', '0002_remove_review_feedback_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
