# Generated by Django 5.0.2 on 2024-03-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_reviews', '0003_review_user_can_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_can_delete',
            new_name='published',
        ),
    ]
