# Generated by Django 5.0.2 on 2024-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_reviews', '0005_remove_review_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
