# Generated by Django 5.0.2 on 2024-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_reviews', '0006_review_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='published',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
