# Generated by Django 5.0.2 on 2024-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
