# Generated by Django 5.0.2 on 2024-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_quantity'),
    ]

    operations = [
        migrations.AddField(
        model_name='listing',
        name='preferred_exchange_method',
        field=models.CharField(default='In-person exchange', help_text='Preferred exchange method', max_length=200),
        preserve_default=False,  # Remove this line if you want to keep existing default values
    ),
    ]
