# Generated by Django 5.0.2 on 2024-02-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
