# Generated by Django 5.0.2 on 2024-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_exchangerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='reason_for_cancellation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
