# Generated by Django 5.0.2 on 2024-03-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_exchangerequest_reason_for_cancellation_and_more'),
        ('messaging', '0008_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation'),
        ),
    ]
