# Generated by Django 5.0.2 on 2024-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_message_listing_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('ER', 'Exchange Request'), ('IA', 'Item Added'), ('DM', 'Direct Message'), ('CM', 'Channel Message')], default='DM', max_length=2),
        ),
    ]
