# Generated by Django 5.0.2 on 2024-03-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='listing',
        ),
    ]
