# Generated by Django 5.0.2 on 2024-03-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_image'),
        ('messaging', '0006_remove_conversation_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing'),
        ),
    ]
