# Generated by Django 5.0.2 on 2024-03-12 07:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_conversation_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
